### ISSUE TITLE
按照流程使用报错，已经debug 模式，webman 是最新版本

### ISSUE THREAD

**Issue by Liubaoqin** [krissss/webman-debugbar#2]
![image](https://user-images.githubusercontent.com/27001235/188356319-b610250b-9cc7-46cc-8920-fab9868499be.png)

**Comment by krissss** [comment]
使用 [webman 安装的流程](https://www.workerman.net/doc/webman/install.html)，安装完后安装该依赖，然后启动webman，访问 _debugbar/sample 后并没有复现你的问题，麻烦提供一下复现流程

**Comment by Liubaoqin** [comment]
我按照顺序执行了
`composer create-project workerman/webman &&
cd ./webman &&
composer require kriss/webman-debugbar
`
然后 php start.php start
![image](https://user-images.githubusercontent.com/27001235/188784766-2d2d0a3e-1038-43a5-9a25-df7c66a18871.png)

启动是正常的，但是当我去访问web地址时
![image](https://user-images.githubusercontent.com/27001235/188784887-2cfa8f11-822d-43b1-9826-eed3b7a6241a.png)
发现不行我配置下app.php
![image](https://user-images.githubusercontent.com/27001235/188785275-7f813afd-6e30-4209-9c15-6605c686bf16.png)
![image](https://user-images.githubusercontent.com/27001235/188785315-b80cae7b-72d5-4fbe-ac15-f53e84ec74a3.png)
内存我设置本机最大还是不行

**Comment by krissss** [comment]
`app.php` 17 行这个 enable 是你自己加的吧，死循环了，去掉这行，包括下面 29-35行，都不要加任何配置

这个扩展的配置在 `config/plugin/kriss/webman-debugbar/` 目录下，不需要复制配置到 `config/app.php` 里的

**Comment by Liubaoqin** [comment]
啊，这就尴尬了，现在已经把配置复原了，并且把包也替换成
`composer require kriss/webman-debugbar --dev`
但还是这样报错
![image](https://user-images.githubusercontent.com/27001235/188801941-cf50d929-fcec-41b2-bc74-bdde27184d50.png)

**Comment by krissss** [comment]
重启没？看看控制台还有报错没

**Comment by Liubaoqin** [comment]
重启了，请求后  控制台也是没有报错的
![image](https://user-images.githubusercontent.com/27001235/188802432-340a31aa-aed5-4ecd-874f-7bfc93393c7f.png)

**Comment by krissss** [comment]
访问链接后是否有报错

**Comment by Liubaoqin** [comment]
这个是有报错的
![image](https://user-images.githubusercontent.com/27001235/188802938-d31c3e19-aafe-4ed8-913a-c7d1d3bb0774.png)

**Comment by krissss** [comment]
webman 的控制台，不是浏览器的

**Comment by Liubaoqin** [comment]
![image](https://user-images.githubusercontent.com/27001235/188803565-bee8acfa-5545-4a64-833c-cf1251d9f0b1.png)
这里没有任何报错

**Comment by krissss** [comment]
麻烦更新一下依赖: `kriss/webman-debugbar --dev`

**Comment by Liubaoqin** [comment]
可以了 ，大佬好厉害

**Comment by Liubaoqin** [comment]
有个问题，如果我请空log ,  然后第一次请求，他是可以正常显示的
但是我在刷新一下，或者别的接口请求，它就变成这样了
![image](https://user-images.githubusercontent.com/27001235/188810073-a4ba7766-67aa-4294-84ce-e85b06f478cb.png)

**Comment by krissss** [comment]
能发一下你说的`别的请求`的接口地址和代码吗（controller或者route）

**Comment by Liubaoqin** [comment]
就是webman 自带的 index 控制器
![image](https://user-images.githubusercontent.com/27001235/188811457-60aeec0d-9b1d-4c1b-a53f-2020e37a0062.png)
![image](https://user-images.githubusercontent.com/27001235/188811514-e5742ae5-b00f-4d9c-9041-ee4de0e39fbc.png)

**Comment by krissss** [comment]
没有复现出来，可以清空一下 runtime/debugbar 目录再试试

**Comment by krissss** [comment]
你的 php 什么版本的

**Comment by Liubaoqin** [comment]
控制台没报错，但是日志记录有报错
![image](https://user-images.githubusercontent.com/27001235/189064747-a34d1153-b1e6-4be4-b0d3-c96615bd0267.png)
我用的8.1
![image](https://user-images.githubusercontent.com/27001235/189064948-4d999033-9ca0-46f8-a913-d0312ad6e749.png)

**Comment by krissss** [comment]
这是 php-debugbar 对 8.1 及之后的兼容性还欠缺导致的
已经有 PR 提交了
https://github.com/maximebf/php-debugbar/pull/510

**Comment by Liubaoqin** [comment]
好的
