### ISSUE TITLE
关于`storage`

### ISSUE THREAD

**Issue by evilk123** [krissss/webman-debugbar#4]
看到代码中,关于`storage `只有file这一个类型吗?
![image](https://user-images.githubusercontent.com/16203922/189661297-d1ce8475-04b8-48fa-96af-5fe357789ea7.png)
因为看到注释说,如果是`file`,会导致文件数极多
所以,想到,是否可以设置redis为`storage`?
如何设置呢?

**Comment by krissss** [comment]
目前没有相应的适配器，可以实现一下StorageInterface接口，如果需要可能得过两天我才能添加

**Comment by evilk123** [comment]
> 目前没有相应的适配器，可以实现一下StorageInterface接口，如果需要可能得过两天我才能添加

好的,谢谢
另外,还有一个问题
如果在线上,通过url来访问这个debugar,如果可以加上鉴权的话,会不会要一点
因为任何人,都可以通过访问这个指定的url,来看到所有的debug信息,会不会不太安全啊?

**Comment by evilk123** [comment]
> 这个自行实现，可以通过middle来实现

ok
谢谢

**Comment by krissss** [comment]
自带支持 RedisStorage 的，用法如下：

`config/plugin/kriss/webman-debugbar/app.php`

```php
<?php

$enable = config('app.debug', false) && class_exists('Kriss\WebmanDebugBar\WebmanDebugBar');

return [
    'enable' => $enable,
    /**
     * @see \Kriss\WebmanDebugBar\WebmanDebugBar::$config
     */
    'debugbar' => [
        'enable' => $enable,
        // 这个配置
        'storage' => function() {
            return new \DebugBar\Storage\RedisStorage(\support\Redis::client());
        }
    ],
];
```
