### ISSUE TITLE
没有看到response-body

### ISSUE THREAD

**Issue by evilk123** [krissss/webman-debugbar#5]
![image](https://user-images.githubusercontent.com/16203922/189665393-dcfecdae-306b-47e4-b962-b20d57209eec.png)
在request一栏中,没有看到response-body相关数据
是设计如此还是?

**Comment by krissss** [comment]
设计如此，因为response_body一般信息量比较大，尤其是html形式的情况下

**Comment by evilk123** [comment]
> 设计如此，因为response_body一般信息量比较大，尤其是html形式的情况下

ok
谢谢
